# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Developer's Portfolio
email: bill@pokeybill.us
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site with links and descriptions of various projects, 
  check out the featured project list.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://portfolio.pokeybill.us" # the base hostname & protocol for your site
include: ['_pages']

# Social media
twitter_username: pokeybill
github_username:  wnormandin

# Encoding (default utf-8, other choices - nil, ASCII-8BIT, etc)
encoding: utf-8

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
